[[timeline]]
year = 2025

[[timeline.items]]
title = "Islantilla w Lily in Aug"
image = "https://images.unsplash.com/photo-1620825632213-43def5fff028?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Belgium & Oma visit in July"
image = "https://images.unsplash.com/photo-1601993305512-a73859a41ec2?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmVsZ2lxdWV8ZW58MHx8MHx8fDA%3D"

[[timeline.items]]
title = "Eisenach w Rudi in June"
image = "https://www.mdr.de/nachrichten/thueringen/west-thueringen/wartburgkreis/eisenach-stadt-wartburg-oben-102_v-variantBig1x1_w-1280_zc-3061602c.jpg?version=8471"

[[timeline.items]]
title = "Belfast & St. Helens w Lily in March"
image = "https://assets-eu-01.kc-usercontent.com/aa24ba70-9a12-01ae-259b-7ef588a0b2ef/77f28f2f-f87e-4ae0-bc6a-707e6ecb4f69/header-tullan-strand-bundoran-donegal.jpg"

[[timeline.items]]
title = "Madrid offsite in Feb"
image = "https://d14fqx6aetz9ka.cloudfront.net/wp-content/uploads/2017/08/11101209/uk_ireland_bundoran.jpg"

[[timeline.items]]
title = "Easkey & Sligo in Feb"
image = "https://mediaim.expedia.com/destination/9/86c7de68993e2dee54ac8170ca54a713.jpg"

[[timeline.items]]
title = "Galway in Jan"
image = "https://images.unsplash.com/photo-1626199749010-cf0f32558395?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"


[[timeline]]
year = 2024

[[timeline.items]]
title = "Fabio & Lara visit Dub in Dec"
image = "https://media.timeout.com/images/106231283/image.jpg"

[[timeline.items]]
title = "Puerto Escondido in Nov"
image = "https://images.unsplash.com/photo-1613684000326-bf2e0cd0ebab?q=80&w=1476&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "San Fransicso in Oct"
image = "https://t3.ftcdn.net/jpg/02/64/88/04/360_F_264880447_47EBgqWIUP1qlfyOSo1Gi79eWR9YzQBu.jpg"

[[timeline.items]]
title = "North Shore in Oct"
image = "https://alohasecrets.com/wp-content/uploads/2021/06/Ehukai_Pillbox_Hike-View_of_Ocean.jpg"

[[timeline.items]]
title = "North Shore in Oct"
image = "https://images.unsplash.com/photo-1583795884587-1a45f3b83d33?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Tokyo in Oct"
image = "https://images.unsplash.com/photo-1554797589-7241bb691973?q=80&w=1336&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Coron in Sep"
image = "https://images.unsplash.com/photo-1584640161267-869f0aa03af6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29yb258ZW58MHx8MHx8fDA%3D"

[[timeline.items]]
title = "Bohol in Sep"
image = "https://images.unsplash.com/photo-1591506557489-e8ca407063e7?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Kuala Lumpur in Sep"
image = "https://images.unsplash.com/photo-1581792343403-f3201559d559?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8a3VhbGElMjBsdW1wdXJ8ZW58MHx8MHx8fDA%3D"

[[timeline.items]]
title = "Singapore in Sep"
image = "https://images.unsplash.com/photo-1569288063643-5d29ad64df09?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNpbmdhcG9yZXxlbnwwfHwwfHx8MA%3D%3D"

[[timeline.items]]
title = "Lombok in Sep"
image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2nRawRPZaqhAgHNmLj2jqqOoXISyrF1E2-g&s"

[[timeline.items]]
title = "Bali in Aug"
image = "https://images.unsplash.com/photo-1569271532860-dd35503aaf1f?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Islantilla in Aug"
image = "https://images.unsplash.com/photo-1620825632213-43def5fff028?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "Munich in July"
image = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTaedQZrkUe6eyE_kixyPQ6axsd9QfOy6hdmyggfEGLECiPM9a_VtTzwxi-2qGrs7bYlBFBHkEYdQn9vKcsNJCVLuBmtx_OP8Zfk-PASw"

[[timeline.items]]
title = "Georgia in May"
image = "https://images.unsplash.com/photo-1603350576276-24747f7bbf40?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline.items]]
title = "County Clare in April"
image = "https://images.unsplash.com/photo-1712431777300-f7d37c0a4d82?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y291bnR5JTIwY2xhcmV8ZW58MHx8MHx8fDA%3D"

[[timeline.items]]
title = "Ireland with AJ in April"
image = "https://images.ireland.com/media/Images/Bundoran/94b55aa9fb0e43e6bae00becf79048c9.jpg"

[[timeline.items]]
title = "Frankfurt in March"
image = "https://i.scdn.co/image/ab67616d00001e021cb2f0e572bf1b18a058af9a"

[[timeline.items]]
title = "Cork in March"
image = "https://static.leonardo-hotels.com/image/Cork_2048x1365_desktop_2.jpeg"

[[timeline.items]]
title = "Lily Dub in Feb"
image = "https://media.timeout.com/images/106231283/image.jpg"

[[timeline.items]]
title = "London in Feb"
image = "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/topic-london-gettyimages-760251843-feature?_a=BAVAZGDX0"

[[timeline]]
year = 2023

[[timeline.items]]
title = "Portugal flexin + Paries in Oct"
image = "https://m4e8m5g9.delivery.rocketcdn.me/wp-content/uploads/2020/03/Ribeira-dIlhas.jpg"

[[timeline.items]]
title = "Turkey w Gang in Sep"
image = "https://rodinistanbul.com/wp-content/uploads/2023/04/day-trips-from-istanbul-copy-1024x576.jpg"

[[timeline.items]]
title = "Munich Culture Week 3 in Aug"
image = "https://www.deutschland.de/sites/default/files/media/image/munich-germany-bavaria-tourism-travel-holidays-alps.jpg"

[[timeline.items]]
title = "Gandia + Liverpool in June"
image = "https://media.istockphoto.com/id/1470047039/photo/gand%C3%ADa-port-grao-beach-aerial-skyline-at-sunset-in-mediterranean-valencia.jpg?s=612x612&w=0&k=20&c=J2JXxqDKx5XLb2IZhoOhuWLy-QNX_tk90553fsvbkho="

[[timeline.items]]
title = "Montenegro in May"
image = "https://lp-cms-production.imgix.net/2023-02/shutterstockRF_252989662.jpg?auto=format,compress&q=72&w=1095&fit=crop&crop=faces,edges"

[[timeline.items]]
title = "Kotlinconf AMS in April"
image = "https://img.nh-hotels.net/a9lpo/8MXbDD/original/Travel+Guides+%E2%80%93+City+Guide+%E2%80%93+Amsterdam+-+bicis+en+canal.jpg"

[[timeline.items]]
title = "Parents & Oma Dub in April"
image = "https://media.timeout.com/images/106231283/image.jpg"

[[timeline.items]]
title = "Taghazout w Cesar & Sophia & Stephen in Mar"
image = "https://cdn.sanity.io/images/we0tdimr/production/9fc43d109d744c0b3f1dc8a51833ad1266887c06-3840x2560.jpg?rect=0,200,3840,2160&w=1920&h=1080&q=70&auto=format"

[[timeline.items]]
title = "Lukas Dub in Feb"
image = "https://www.blookery.de/blog/wp-content/uploads/2017/03/dublin_sehenswu%CC%88rdigkeiten.png"

[[timeline.items]]
title = "Northern Spain flexin in Jan"
image = "https://cms.guggenheim-bilbao.eus/uploads/2021/03/1.jpg"

[[timeline]]
year = 2022

[[timeline.items]]
title = "Portugal w Cuzao in Oct"
image = "https://m4e8m5g9.delivery.rocketcdn.me/wp-content/uploads/2020/03/Ribeira-dIlhas.jpg"

[[timeline.items]]
title = "Morocco in Sep"
image = "https://youshouldgohere.com/wp-content/uploads/2019/01/IMG_3557-1250x750.jpg"

[[timeline.items]]
title = "Muc w Lis in July"
image = "https://www.deutschland.de/sites/default/files/media/image/munich-germany-bavaria-tourism-travel-holidays-alps.jpg"

[[timeline.items]]
title = "Rome w Fam in June"
image = "https://www.touristitaly.com/wp-content/uploads/2023/03/Trevi-Fountain-rome-2-1024x683.jpg"

[[timeline.items]]
title = "Rudi in Dub in June"
image = "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/bltfad3877ec10c226b/674ec21348603bf0fe49bce7/BCC-2024-EXPLORER-DUBLIN-FUN-THINGS-TO-DO-HEADER_MOBILE.jpg?format=webp&quality=60&width=1440"

[[timeline.items]]
title = "Sophia in Dub in June"
image = "https://media.timeout.com/images/106231283/image.jpg"

[[timeline.items]]
title = "Yucatan in May"
image = "https://cdn.sanity.io/images/atvntylo/production/c5444922a0cd9ffe8c1f8b4ccefa12867c899823-1200x720.webp?w=3840&q=65&fit=clip&auto=format"

[[timeline.items]]
title = "Dingle in Feb"
image = "https://images.ireland.com/thumbs/Images/dingle-peninsula-trip-idea/1167404d46f14d6289cc415e939426b0/collagebackground-desktop.jpg"

[[timeline]]
year = 2021

[[timeline.items]]
title = "Malta in Dec"
image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtAMbOQGzc4velBHCF5XuiKYKAEsHLTFsUKbbhDESEWcTBOLfo1gZe00ZrVOVBNS32k-4&usqp=CAU"

[[timeline.items]]
title = "Madeira in Sep"
image = "https://ik.imgkit.net/3vlqs5axxjf/TAW/ik-seo/uploadedImages/All_Gateways/Europe/Features/madeiradestinationguidelbeach/madeiraislandportugalvisit.jpg?tr=w-1008%2Ch-567%2Cfo-auto"

[[timeline.items]]
title = "First time Bundoran in June"
image = "https://discoverbundoran.com/wp-content/uploads/2023/05/Discovering-Begins-Here-1-1024x732.jpg"

[[timeline]]
year = 2020

[[timeline.items]]
title = "Extreme Flexin Islantilla Sep"
image = "https://images.unsplash.com/photo-1620825632213-43def5fff028?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[timeline]]
year = 2019

[[timeline.items]]
title = "Arrive Dub 12. Nov"
image = ""

[[timeline.items]]
title = "Jackdilac trip w Fabio in Sep"
image = ""

[[timeline.items]]
title = "Vienna in Jun"
image = ""

[[timeline]]
year = 2018

[[timeline.items]]
title = "Gent w Friends in Sep"
image = "https://images.unsplash.com/photo-1601993305512-a73859a41ec2?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmVsZ2lxdWV8ZW58MHx8MHx8fDA%3D"

[[timeline]]
year = 2017

[[timeline.items]]
title = "Roadtrip Westcoast USA w Lis in July"
image = ""

[[timeline.items]]
title = "Cruise and NYC w Fam in Jun"
image = ""

[[timeline.items]]
title = "Ski in Mar"
image = ""

[[timeline]]
year = 2016

[[timeline.items]]
title = "Rock am Ring in Jun"
image = ""

[[timeline.items]]
title = "Kappl in Mar"
image = ""

[[timeline]]
year = 2015

[[timeline.items]]
title = "Cork Semester"
image = ""

[[timeline.items]]
title = "Rock am Ring in Jun"
image = ""

[[timeline]]
year = 2014

[[timeline.items]]
title = "Sms in Aug"
image = ""

[[timeline.items]]
title = "Southside in Jun"
image = ""
